### ISSUE TITLE
Clarify what can/should be close! ed

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDatabases/DBInterface.jl#23]
Right now the README looks like one can close statements, but presumably one can also close results and connections?

Maybe it would be good if the convention for users of the API is that they actually _should_ call `close!` on connections, statements and results?

**Comment by quinnj** [comment]
Ok, we've recently updated the docs on `close!` and I just fixed the docs generation, which can be seen here: https://juliadatabases.org/DBInterface.jl/dev/
