### ISSUE TITLE
Why isn't Base.close used?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDatabases/DBInterface.jl#24]
That seems exactly the right function?

**Comment by quinnj** [comment]
It's safer to make our own interface function here; `Base.close` has certain semantics and meaning and we may not want to follow or guarantee the same things. We discovered this in Tables.jl w/ relying on `getproperty` and `propertynames`; there might be certain types/scenarios where `Base.close` is already defined and already has a defined behavior and it's awkward to overload now for DBInterface.

Requiring our own `DBInterface.close!` lets us avoid any weirdness in all of that.
