### ISSUE TITLE
Replace `NotImplementedError`s with `MethodError`s

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDatabases/DBInterface.jl#27]
- `MethodErrors` convey this same information, with the bonus of showing "closest candidates"
- Since all the functions here belong to the `DBInterface` namespace (we're not e.g. adding methods to Base functions), the `MethodErrors` should be particularly helpful 
- Furthermore, in a few cases the message in the `NotImplementedError` may just be incorrect
  - e.g. in 
    ```julia
     connect(T, args...; kw...) = throw(NotImplementedError("`DBInterface.connect` not implemented for `$T`"))
    ``` 
     there may be methods for `T`, but not for the given `args`
  - this is discussed at the start of this blog https://white.ucc.asn.au/2020/04/19/Julia-Antipatterns.html
  - instead we can just define a function with a docstring and no methods
    ```julia
    """docstring"""
    function connect end
    ```
- This also would remove quite a few lines of code at no cost

**Comment by quinnj** [comment]
Yeah, I'd be fine w/ doing this if you want to put up a PR
