### ISSUE TITLE
`executemultiple` fallback only `execute`s the first statement.

### ISSUE THREAD

**Issue by joshday** [JuliaDatabases/DBInterface.jl#42]
https://github.com/JuliaDatabases/DBInterface.jl/blob/a2734ab81c2fde572d8ebe59330c0f02c89458c2/src/DBInterface.jl#L219

Not sure if the line above is the right place for an error/warning, but I would expect something in the pipeline to tell me that `SQLite.jl` doesn't support `executemultiple`.

```Julia
julia> db = SQLite.DB();

julia> DBInterface.executemultiple(db, "CREATE TABLE temp(x INTEGER); CREATE TABLE temp2(x INTEGER);");

julia> SQLite.tables(db)
(name = ["temp"],)
```

**Comment by quinnj** [comment]
This isn't a DBInterface thing, but an sqlite thing, in that it doesn't support executing multiple statements at a time (note not an SQLite.jl thing, but _sqlite_ thing).
