### ISSUE TITLE
Executemany does not work

### ISSUE THREAD

**Issue by jakobnissen** [JuliaDatabases/DBInterface.jl#43]
```
julia> DBInterface.executemany(stmt,
           (
               lnums,
               owner,
               segments,
               seqs,
               datetimes,
               datetimes,
               len
           )
       )
ERROR: MethodError: no method matching getconnection(::ODBC.Statement)
Stacktrace:
 [1] executemany(stmt::ODBC.Statement, params::Tuple{Vector{String}, Vector{String}, Vector{String}, Vector{String}, Vector{String}, Vect
or{String}, Vector{Int64}})
   @ DBInterface ~/.julia/packages/DBInterface/1Gmxx/src/DBInterface.jl:193
 [2] top-level scope
   @ REPL[106]:1
```
I'm not sure why, but it looks like just a missing implementation of a method?

**Comment by jfb-h** [comment]
Same case for SQLite, here's an MWE:

```julia
using DBInterface, SQLite

db = SQLite.DB()
DBInterface.execute(db, "CREATE TABLE t (x INTEGER, y TEXT)")
stmt = DBInterface.prepare(db, """INSERT INTO t VALUES (:x, :y)""")
DBInterface.executemany(stmt, (x=[1,2,3,4], y=["a", "b", "c", "d"]))
```
This returns:

```julia
ERROR: MethodError: no method matching getconnection(::SQLite.Stmt)
Stacktrace:
 [1] executemany(stmt::SQLite.Stmt, params::NamedTuple{(:x, :y), Tuple{Vector{Int64}, Vector{String}}})
   @ DBInterface C:\Users\Jakob\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:193
 [2] top-level scope
   @ REPL[40]:1
```

**Comment by lawless-m** [comment]
It's not executemany at fault but getconnection

julia> DBInterface.getconnection(stmt)
ERROR: MethodError: no method matching getconnection(::ODBC.Statement)
Stacktrace:
 [1] top-level scope
   @ REPL[22]:1

**Comment by lawless-m** [comment]
I created a PR to fix this missing function

**Comment by lawless-m** [comment]
> Same case for SQLite, here's an MWE:
> 
> ```julia
> using DBInterface, SQLite
> 
> db = SQLite.DB()
> DBInterface.execute(db, "CREATE TABLE t (x INTEGER, y TEXT)")
> stmt = DBInterface.prepare(db, """INSERT INTO t VALUES (:x, :y)""")
> DBInterface.executemany(stmt, (x=[1,2,3,4], y=["a", "b", "c", "d"]))
> ```
> 
> This returns:
> 
> ```julia
> ERROR: MethodError: no method matching getconnection(::SQLite.Stmt)
> Stacktrace:
>  [1] executemany(stmt::SQLite.Stmt, params::NamedTuple{(:x, :y), Tuple{Vector{Int64}, Vector{String}}})
>    @ DBInterface C:\Users\Jakob\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:193
>  [2] top-level scope
>    @ REPL[40]:1
> ```

this has already been fixed in SQLite

**Comment by quinnj** [comment]
Looks like both cases have been fixed now; thanks all.
