### ISSUE TITLE
Document which packages implement `DBI`

### ISSUE THREAD

**Issue by cgoldammer** [JuliaDatabases/DBInterface.jl#7]
It'd be great if the beginning of the documentation would provide a list of the packages that implement the interface/API of `DBI.jl`. I'm pretty sure that includes: [SQLite.jl](https://github.com/quinnj/SQLite.jl) and [MySQL.jl](https://github.com/johnmyleswhite/MySQL.jl) but I'm not sure about others.

I'm planning to mention this in my added documentation for `DataFrames`, where I want to include, in the IO section, how to obtain a `DataFrame` from a database.

**Comment by iamed2** [comment]
It includes MySQL.jl and PostgreSQL.jl, but not SQLite.jl. I think @johnmyleswhite was working on https://github.com/JuliaDB/DBDSQLite.jl but I'm not sure what the status of that package is. I believe those are the only ones. I'll update if jmw can say something about the status of his SQLite package.

**Comment by johnmyleswhite** [comment]
My SQLite package isn't likely to be updated for a very long time to come. And the MySQL package I started working on isn't finished.

Other than @iamed2's PostgreSQL, I think a lot more work is needed to make DBI a reality for Julia. Most of the work done on database hasn't been done with an eye towards cross-database compatibility.

**Comment by iamed2** [comment]
Stay tuned for a reboot from me any day now :-)

**Comment by quinnj** [comment]
On the README, we now include a link to the JuliaHub page where you can see all direct dependents (https://github.com/JuliaDatabases/DBInterface.jl/commit/3d84a7da38c8b0e0fdcb416bf10b0df133d4c062)
